apiVersion: v1
kind: Service
metadata:
  name: pgdatalayer
spec:
  selector:
    app: pgdatalayer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP #if I won't use Ingress API: LoadBalancer