apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgdatalayer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pgdatalayer
  template:
    metadata:
      labels:
        app: pgdatalayer
    spec:
      containers:
      - name: pgecommerce
        image: hftamayo/pgecommerce:0.0.1
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pgdata-pvc
      imagePullSecrets:
      - name: regcred