apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: app-production

# Reference to base configuration
resources:
- ../../base

# Environment-specific namespace
namespace: vanillatstodo-prod

# Dynamic naming using global config
namePrefix: vanillatstodo-
nameSuffix: -prod

# Environment-specific labels
commonLabels:
  environment: production
  app.kubernetes.io/name: vanillatstodo
  app.kubernetes.io/part-of: vanillatstodo

# Environment-specific annotations
commonAnnotations:
  environment: production
  cost-center: production
  backup: enabled
  monitoring: enhanced

# Override Helm values for production environment
helmCharts:
- name: app
  releaseName: app
  valuesInline:
    app:
      environment: production
    deployment:
      replicas: 3 # High availability
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    healthChecks:
      readinessProbe:
        initialDelaySeconds: 30
      livenessProbe:
        initialDelaySeconds: 60
    security:
      enabled: true # Full security for production
      runAsNonRoot: true
      runAsUser: 1000
    monitoring:
      prometheus:
        scrape: "true"

# Production uses stable tags
images:
- name: hftamayo/vanillatstodo
  newTag: "0.0.1" # Stable production tag
