# Production Environment Configuration
app:
  name: vanillatstodo
  version: "0.0.1"
  environment: production

image:
  repository: hftamayo/vanillatstodo
  tag: "0.0.1"
  pullPolicy: IfNotPresent

deployment:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
  externalTrafficPolicy: Local

healthChecks:
  enabled: true # Enable for production
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 15
    periodSeconds: 20

security:
  enabled: true # Enable for production
  runAsNonRoot: true
  runAsUser: 1000

imagePullSecrets:
  - name: regcred

monitoring:
  prometheus:
    scrape: true
    port: "80"
