apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: app-experimental

# Reference to base configuration
resources:
- ../../base

# Environment-specific namespace
namespace: vanillatstodo-exp

# Dynamic naming using global config
namePrefix: vanillatstodo-
nameSuffix: -exp

# Environment-specific labels
commonLabels:
  environment: experimental
  app.kubernetes.io/name: vanillatstodo
  app.kubernetes.io/part-of: vanillatstodo

# Environment-specific annotations
commonAnnotations:
  environment: experimental
  cost-center: development

# Override Helm values for experimental environment
helmCharts:
- name: app
  releaseName: app
  valuesInline:
    app:
      environment: experimental
    deployment:
      replicas: 1 # Minimal resources for development
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    service:
      type: LoadBalancer # Easy external access for testing
    healthChecks:
      readinessProbe:
        initialDelaySeconds: 10 # Faster startup for development
      livenessProbe:
        initialDelaySeconds: 20
    security:
      enabled: false # Relaxed security for development

# Dynamic image tag (will be set by CI/CD)
images:
- name: hftamayo/vanillatstodo
  newTag: experimental-latest
