apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to base configuration
bases:
- ../../base

# Environment-specific labels
commonLabels:
  environment: experimental

# Environment-specific annotations
commonAnnotations:
  environment: experimental
  cost-center: development

# Override Helm values for experimental environment
helmCharts:
- name: vanillatstodo-app
  releaseName: vanillatstodo-experimental
  valuesInline:
    app:
      environment: experimental
    deployment:
      replicas: 1 # Minimal resources for development
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    service:
      type: LoadBalancer # Easy external access for testing
    healthChecks:
      readinessProbe:
        initialDelaySeconds: 10 # Faster startup for development
      livenessProbe:
        initialDelaySeconds: 20
    security:
      enabled: false # Relaxed security for development

# Dynamic image tag (will be set by CI/CD)
images:
- name: hftamayo/vanillatstodo
  newTag: experimental-latest
