apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: app-staging

# Reference to base configuration
resources:
- ../../base

# Environment-specific namespace
namespace: vanillatstodo-staging

# Dynamic naming using global config
namePrefix: vanillatstodo-
nameSuffix: -staging

# Environment-specific labels
commonLabels:
  environment: staging
  app.kubernetes.io/name: vanillatstodo
  app.kubernetes.io/part-of: vanillatstodo

# Environment-specific annotations
commonAnnotations:
  environment: staging
  cost-center: qa

# Override Helm values for staging environment
helmCharts:
- name: app
  releaseName: app
  valuesInline:
    app:
      environment: staging
    deployment:
      replicas: 2 # Production-like but smaller
    resources:
      requests:
        cpu: "150m"
        memory: "256Mi"
      limits:
        cpu: "300m"
        memory: "512Mi"
    service:
      type: ClusterIP # Internal access only, use port-forward
    healthChecks:
      readinessProbe:
        initialDelaySeconds: 30
      livenessProbe:
        initialDelaySeconds: 60
    security:
      enabled: true # Enhanced security for staging
      runAsNonRoot: true
      runAsUser: 1000

# Dynamic image tag (will be set by CI/CD)
images:
- name: hftamayo/vanillatstodo
  newTag: staging-latest
