apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: monitoring-production

# Reference the base configuration
resources:
- ../../base
- resource-quota.yaml

# Environment-specific namespace
namespace: monitoring-prod

# Dynamic naming using global config
namePrefix: vanillatstodo-
nameSuffix: -prod

# Environment-specific labels
commonLabels:
  environment: production
  monitoring.io/env: production
  monitoring.io/criticality: high
  app.kubernetes.io/name: vanillatstodo-monitoring
  app.kubernetes.io/part-of: vanillatstodo

# Patches for production environment
patches:
- target:
    kind: HelmRelease
    name: monitoring
  patch: |-
    - op: replace
      path: /spec/values/global/environment
      value: production
    - op: replace
      path: /spec/values/prometheus-stack/prometheus/prometheusSpec/retention
      value: 30d
    - op: replace
      path: /spec/values/prometheus-stack/prometheus/prometheusSpec/retentionSize
      value: 10GB
    - op: replace
      path: /spec/values/prometheus-stack/prometheus/prometheusSpec/storageSpec/volumeClaimTemplate/spec/resources/requests/storage
      value: 50Gi
    - op: replace
      path: /spec/values/prometheus-stack/prometheus/prometheusSpec/resources/limits/cpu
      value: 1000m
    - op: replace
      path: /spec/values/prometheus-stack/prometheus/prometheusSpec/resources/limits/memory
      value: 4Gi
    - op: replace
      path: /spec/values/prometheus-stack/prometheus/prometheusSpec/resources/requests/cpu
      value: 500m
    - op: replace
      path: /spec/values/prometheus-stack/prometheus/prometheusSpec/resources/requests/memory
      value: 2Gi
    - op: replace
      path: /spec/values/prometheus-stack/grafana/adminPassword
      value: production-super-secure-password
    - op: replace
      path: /spec/values/prometheus-stack/grafana/persistence/size
      value: 20Gi
    - op: replace
      path: /spec/values/prometheus-stack/grafana/resources/limits/cpu
      value: 500m
    - op: replace
      path: /spec/values/prometheus-stack/grafana/resources/limits/memory
      value: 1Gi
    - op: replace
      path: /spec/values/prometheus-stack/grafana/resources/requests/cpu
      value: 250m
    - op: replace
      path: /spec/values/prometheus-stack/grafana/resources/requests/memory
      value: 512Mi
    - op: replace
      path: /spec/values/prometheus-stack/alertmanager/enabled
      value: true
    - op: replace
      path: /spec/values/prometheus-stack/alertmanager/alertmanagerSpec/storage/volumeClaimTemplate/spec/resources/requests/storage
      value: 10Gi
    - op: replace
      path: /spec/values/serviceMonitor/interval
      value: 15s
    - op: replace
      path: /spec/values/serviceMonitor/scrapeTimeout
      value: 5s
    - op: replace
      path: /spec/values/ingress/grafana/enabled
      value: true
    - op: replace
      path: /spec/values/ingress/grafana/host
      value: grafana-prod.vanillatstodo.com
    - op: replace
      path: /spec/values/ingress/prometheus/enabled
      value: true
    - op: replace
      path: /spec/values/ingress/prometheus/host
      value: prometheus-prod.vanillatstodo.com

# ConfigMap patches for production-specific monitoring configs
configMapGenerator:
- name: monitoring-config
  literals:
  - environment=production
  - retention=30d
  - log_level=warn
  - metrics_interval=15s
  - alerting_enabled=true
  - high_availability=true
  - backup_enabled=true
