name: "Destroy Infrastructure"

"on":
  workflow_dispatch:
    inputs:
      confirmation:
        description: "Type 'destroy' to confirm"
        required: true
        type: string

  push:
    branches:
      - staging
      - experimental
    paths:
      - "devops/terraform/**"

permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    name: "Destroy Infrastructure"
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirmation == 'destroy' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.7.0"

      - name: Import Existing Resources
        run: |
          pwd  # Debug current directory
          ls -la devops/scripts/  # Verify script exists
          chmod +x devops/scripts/import-resources.sh
          ./devops/scripts/import-resources.sh

      - name: Destroy EKS Layer
        working-directory: devops/terraform/02_eks
        run: |
          terraform init
          terraform destroy -auto-approve || {
            echo "❌ EKS destroy failed"
            exit 1
          }

      - name: Destroy Network Layer
        working-directory: devops/terraform/01_network
        run: |
          terraform init
          terraform destroy -auto-approve || {
            echo "❌ Network destroy failed"
            exit 1
          }

      - name: Destroy State Layer
        working-directory: devops/terraform/00_state
        run: |
          terraform init
          terraform destroy -auto-approve || {
            echo "❌ State destroy failed"
            exit 1
          }

          echo "✅ Infrastructure destroyed successfully"
