name: "Destroy Infrastructure"

"on":
  workflow_dispatch:
    inputs:
      confirmation:
        description: "Type 'destroy' to confirm"
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    name: "Destroy Infrastructure"
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirmation == 'destroy' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.7.0"

      - name: Destroy EKS Resources
        run: |
          CLUSTER_NAME="vanillatstodo-cluster"

          echo "🔍 Checking for EKS node groups..."
          NODE_GROUPS=$(aws eks list-nodegroups --cluster-name $CLUSTER_NAME --query 'nodegroups[*]' --output text || echo "")

          if [ ! -z "$NODE_GROUPS" ]; then
            echo "Found node groups: $NODE_GROUPS"
            for ng in $NODE_GROUPS; do
              echo "🗑️ Deleting node group: $ng"
              aws eks delete-nodegroup --cluster-name $CLUSTER_NAME --nodegroup-name $ng
              echo "⏳ Waiting for node group deletion..."
              aws eks wait nodegroup-deleted --cluster-name $CLUSTER_NAME --nodegroup-name $ng
            done
          fi

          echo "🗑️ Deleting EKS cluster..."
          aws eks delete-cluster --name $CLUSTER_NAME
          echo "⏳ Waiting for cluster deletion..."
          aws eks wait cluster-deleted --name $CLUSTER_NAME

      - name: Clean Up Network Resources
        run: |
          echo "🔍 Finding VPC resources..."
          VPC_ID=$(aws ec2 describe-vpcs --filters "Name=tag:Name,Values=*vanillatstodo*" --query 'Vpcs[0].VpcId' --output text)

          if [ "$VPC_ID" != "None" ]; then
            echo "Found VPC: $VPC_ID"
            
            # Delete Internet Gateway
            IGW_ID=$(aws ec2 describe-internet-gateways --filters "Name=attachment.vpc-id,Values=$VPC_ID" --query 'InternetGateways[0].InternetGatewayId' --output text)
            if [ "$IGW_ID" != "None" ]; then
              echo "🗑️ Detaching and deleting Internet Gateway..."
              aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID
              aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID
            fi
            
            # Delete Subnets
            SUBNET_IDS=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" --query 'Subnets[*].SubnetId' --output text)
            for subnet in $SUBNET_IDS; do
              echo "🗑️ Deleting subnet: $subnet"
              aws ec2 delete-subnet --subnet-id $subnet
            done
            
            # Delete VPC
            echo "🗑️ Deleting VPC..."
            aws ec2 delete-vpc --vpc-id $VPC_ID
          fi
